name: plannet
services:
  frontend:
    build:
      context: .
      dockerfile: FE.Dockerfile
    ports:
      - "3188:80"

  backend:
    build:
      context: .
      dockerfile: BE.Dockerfile
    ports:
      - "5000:5000"
